name: auto update

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: fopina/upstream-to-pr@feature/latest_tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upstream-repository: https://github.com/OJ/gobuster
          upstream-tag: 'v\d+\.\d+\.\d+'
